version: "3"

services:
  python3:

    build: .
    container_name: "python3_bot"
    working_dir: "/root/"
    ports:
      - "230:230"
    tty: true
    volumes:
      - ./opt:/root/

  db:
    image: postgres:alpine
    # ports:
    # - "5432:5432"
    volumes:
      - "data-base:/var/lib/postgres/data/"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  yarn-cache:
  node_modules_volume:
  data-base:
